### ISSUE TITLE
Faceted decomposition graphs for Classic, STL, and X-13 ARIMA SEATS similar to default plotting of class "stl"

### ISSUE THREAD

**Issue by paulhendricks** [ellisp/ggseas#1]
Great package. What would you think of possibly implementing functionality that provides a facet of decomposition similar to the default plotting of an "stl" class.

In code, something that mimics this:

``` r
some_ts <- ts(rnorm(100), frequency = 12)
plot(stl(some_ts, s.window = "periodic"))
```

But with ggplot2 styles and similar to your API. Maybe a `facet = TRUE` flag?

``` r
library(ggseas)
# make demo data
ap_df <- data.frame(
   x = as.numeric(time(AirPassengers)),
   y = as.numeric(AirPassengers)
)

ggplot(ap_df, aes(x = x, y = y)) +
   geom_line(colour = "grey80") +
   stat_decomp(frequency = 12, facet = TRUE)
```

**Comment by ellisp** [comment]
I've got an idea to do this but I don't think it will be a stat or a geom; more a wrapper like `GGally::ggpairs`.  The most obvious thing to do is to use facets, which means it won't fit simply into the ggplot structure.   Will have a go some time soonish.

**Comment by ellisp** [comment]
I've had a go at this and created a new `ggsdc()` function which you 

can access in the GitHub version

``` R
devtools::install_github("ellisp/ggseas/pkg")
ggsdc(ldeaths_df, aes(x = YearMon, y = deaths, colour = sex), method = "seas", 
      frequency = 12, start = c(1949, 1)) +
      geom_line()
```

![unnamed-chunk-6-3](https://cloud.githubusercontent.com/assets/5740570/13200163/8feea660-d8a1-11e5-9b7e-da3a0f05452a.png)

Let me know what you think - and any stress tresting you can think of would be appreciated too.  I'm not sure how robust it is, particularly for the X13-SEATS-ARIMA connection.
