### ISSUE TITLE
Is there any way to change facet names in ggsdc?

### ISSUE THREAD

**Issue by sillasgonzaga** [ellisp/ggseas#11]
My native language in Portuguese and I'm writing my undergraduate thesis in which I will show a plot made by using ggsdc(). I wonder if I can manually change the facets names so I can write what they mean in Portuguese.

**Comment by ellisp** [comment]
Not yet, but I'll add it to the next version.

**Comment by ellisp** [comment]
OK, this was easier than I thought.  If you install the GitHub version you should be able to do this now with the new facet.titles argument to `ggsdc()`.  It works with UTF-8 characters too in case you need them.  Let me know how it goes.

``` R
devtools::install_github("ellisp/ggseas/pkg")
```

**Comment by sillasgonzaga** [comment]
Thanks. It works indeed.
